apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pfte1x5t9-python-gitops
  description: This is GitOps manifest for pfte1x5t9-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=pfte1x5t9-python
    backstage.io/kubernetes-id: pfte1x5t9-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: pfte1x5t9-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:pfte1x5t9-python
